package model;

import java.util.List;

/**
 * A body of water on the map (river, lake, etc.).
 *
 * <p>Water tiles block road construction; players must build bridges across them.
 * The shape can be rectangular (auto-generated footprint) or irregular (custom tile list
 * used for rivers and lakes generated by {@link MapGenerator}).
 */
public class WaterBody extends MapEntity {

    /**
     * Creates a water body with an auto-generated rectangular footprint.
     *
     * @param id      unique entity identifier
     * @param name    display name (e.g. "Silver River")
     * @param originX top-left column of the bounding rectangle
     * @param originY top-left row of the bounding rectangle
     * @param width   width in tiles
     * @param height  height in tiles
     */
    public WaterBody(String id, String name, int originX, int originY, int width, int height) {
        super(id, name, originX, originY, width, height);
    }

    /**
     * Creates a water body with an irregular (non-rectangular) tile set.
     * The {@code customTiles} list replaces the auto-generated rectangular footprint,
     * allowing rivers and lakes with arbitrary shapes.
     *
     * @param id          unique entity identifier
     * @param name        display name
     * @param originX     top-left column of the bounding rectangle
     * @param originY     top-left row of the bounding rectangle
     * @param width       width of the bounding rectangle
     * @param height      height of the bounding rectangle
     * @param customTiles explicit list of tiles that make up this water body
     */
    public WaterBody(String id, String name, int originX, int originY, int width, int height, List<Position> customTiles) {
        super(id, name, originX, originY, width, height);
        this.tiles.clear();
        this.tiles.addAll(customTiles);
    }
}
